//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cSharpLocalization.LangResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cSharpLocalization.LangResources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! {0} degrees Fahrernheit! That&apos;s freezing!!!.
        /// </summary>
        internal static string coldTemp {
            get {
                return ResourceManager.GetString("coldTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay, {0} degrees Fahrernheit isn&apos;t exactly warm. Don&apos;t forget a coat!.
        /// </summary>
        internal static string coolTemp {
            get {
                return ResourceManager.GetString("coolTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me the temperature in Fahrenheit where you&apos;re at, right now? Quick! It&apos;s urgent!.
        /// </summary>
        internal static string currentTemp {
            get {
                return ResourceManager.GetString("currentTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time in our newly selected culture is {0}..
        /// </summary>
        internal static string dateTime {
            get {
                return ResourceManager.GetString("dateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your first name?.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye {0} {1}.
        /// </summary>
        internal static string goodbye {
            get {
                return ResourceManager.GetString("goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon. Hit any key to continue.
        /// </summary>
        internal static string greetAfternoon {
            get {
                return ResourceManager.GetString("greetAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening. Hit any key to continue.
        /// </summary>
        internal static string greetEvening {
            get {
                return ResourceManager.GetString("greetEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} {1}.
        /// </summary>
        internal static string greeting {
            get {
                return ResourceManager.GetString("greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning. Hit any key to continue.
        /// </summary>
        internal static string greetMorning {
            get {
                return ResourceManager.GetString("greetMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMG!!! {0} degrees Fahrernheit is way too hot! Stay indoors!!!.
        /// </summary>
        internal static string hotTemp {
            get {
                return ResourceManager.GetString("hotTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I knew you&apos;d quit. Wimp!.
        /// </summary>
        internal static string isoError0 {
            get {
                return ResourceManager.GetString("isoError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice try but you got it wrong. Try again.  Choose from en-US, es-ES, fr-FR, de-DE..
        /// </summary>
        internal static string isoError1 {
            get {
                return ResourceManager.GetString("isoError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language by writing its ISO code or hit ENTER to quit. Choose from en-US, es-ES, fr-FR, de-DE.
        /// </summary>
        internal static string isoPrompt {
            get {
                return ResourceManager.GetString("isoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose {0}..
        /// </summary>
        internal static string isoSuccess {
            get {
                return ResourceManager.GetString("isoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me your last name?.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again! Write your name once more.
        /// </summary>
        internal static string nameError {
            get {
                return ResourceManager.GetString("nameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t want to do it anyay..
        /// </summary>
        internal static string reject {
            get {
                return ResourceManager.GetString("reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures don&apos;t sound as extreme when converted to Celsius. Would you like me to convert the temperature to Celsius? Write Y for YES and N for NO..
        /// </summary>
        internal static string tempConv {
            get {
                return ResourceManager.GetString("tempConv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} degrees Fahreinheit = {1} degrees Celcius.
        /// </summary>
        internal static string tempConvResults {
            get {
                return ResourceManager.GetString("tempConvResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit ENTER for good news..
        /// </summary>
        internal static string tempNews {
            get {
                return ResourceManager.GetString("tempNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} degrees Fahrernheit. That&apos;s quite warm. Don&apos;t forget your sunscreen!.
        /// </summary>
        internal static string warmTemp {
            get {
                return ResourceManager.GetString("warmTemp", resourceCulture);
            }
        }
    }
}
